config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'welcome/index'
  resources :docs

  authenticated :user do
    root 'docs#index', as: 'authenticated_root'
  end
  root 'welcome#index'
  # 失敗！！沒效果

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user

  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :docs      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

  before_action :authenticate_user!
 
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.where( user_id: current_user).order(created_at: :desc)
    # 只有他自己(current_user)的Docs
  end

  def show
  end

  def new
    @doc = current_user.docs.new
  end

  def create
    @doc = current_user.docs.new(doc_params)
    if @doc.save
      redirect_to doc_path(@doc)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to doc_path(@doc)
    else
      render :edit
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

  def doc_params
    params.require(:doc).permit(:title, :content, :user_id, :photo)
  end

  def find_doc
    @doc = Doc.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= form_for doc do |d| %>

  <%= d.label :title %>
  <%= d.text_field :title %><br />

  <%= d.label :content %>
  <%= d.text_field :content %><br />

  <%= d.label :photo %>
  <%= image_tag @doc.photo, width: '300px' if @doc.photo? %>
  <%= d.file_field :photo %><br />  

  <%= d.submit %>

<% end %>

app/views/docs/edit.html.erb
<h1>Edit Doc</h1>

<%= render partial: 'form', locals: { doc: @doc} %>

app/views/docs/index.html.erb
<div class="container">
  <div class="row">

    <h1 class="text-center">Docs list</h1>

    <h3><%= link_to 'New Doc ', new_doc_path %></h3>
    <br>

    <table class="table table-striped table-bordered" > 
      <tr>
        <th>Ttile</th>
        <th>Content</th>
        <th>Create_at</th>
        <th>Docs_id</th>
        <th>User_id</th>
        <th>#</th>
      </tr>
      <tr>
      <% @docs.each do |d| %>
      <td><%= d.title %></td>
        <td><%= d.content %></td>
        <td><%= time_ago_in_words(d.created_at) %></td>
        <td><%= d.id %></td>
        <td><%= d.user_id %></td>
        <td><%= link_to 'Show', doc_path(d) %>
        <%= link_to 'Edit', edit_doc_path(d) %>
        <%= link_to 'Trash it', doc_path(d), method: :delete, data: { confirm: "Areyou sure? "} %></td>
      </tr>
      <% end %>
    </table>

    
  </div>
</div>

app/views/docs/new.html.erb
<h1>New doc</h1>

<%= render partial: 'form', locals: { doc: @doc} %>

app/views/docs/show.html.erb
<h1>Show Doc</h1>
Title:<%= @doc.title %><br />
Content:<%= @doc.content %><br>
<%= image_tag @doc.photo, width: '700px' %>

<br>

<%= link_to 'Back to Docs', docs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cabinet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "File Cabinet", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="pull-right text-right nav navbar-nav">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hi, <%= current_user.email %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Fake Profile', docs_path %></li>
                  <li><%= link_to "Change Password", edit_user_registration_path %></li>
                </ul>
              <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
            <% else %>
              <li><%= link_to('註冊', new_user_registration_path) %></li>
              <li><%= link_to('登入', new_user_session_path) %></li>
            <% end %>

          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row text-center">
    <h1>File Cabinet</h1>
    <br>
    <h3>Your live's work! Organized, always.</h3>
    <%= image_tag('1.jpg', class:'img-responsive center-block')  %>

    <% if current_user %>
      <h1><%= link_to 'Enter', docs_path %></h1>
    <% else %>
      <h3>See more content sign up here | <%= link_to 'Join Now', new_user_registration_path  %> </h3>
    <% end %>   
  </div>
</div>